=== enzoley/table-zelda/src/V1/jeux.dtd
<!ELEMENT nomDeJeu (#PCDATA)>
<!ELEMENT dateDeSortie (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT multijoueur (#PCDATA)>
<!ELEMENT theme (#PCDATA)>
<!ELEMENT classification (#PCDATA)>
<!ELEMENT jeu (nomDeJeu, dateDeSortie, description, note?, multijoueur, theme?, classification?)>
<!ELEMENT timeline (nomDeTimeline,jeu+)>
<!ELEMENT jeux (timeline)+>
<!ELEMENT nomDeTimeline (#PCDATA)>
<!ATTLIST timeline id ID #REQUIRED>
<!ATTLIST jeu id ID #REQUIRED>

=== enzoley/table-zelda/src/V2/jeux.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="../V1/jeux.css" type="text/css"?>
<!DOCTYPE jeux SYSTEM "jeux.dtd">
<jeux>
    <timeline id="tradition">
        <nomDeTimeline>La tradition divine et le héros du temps</nomDeTimeline>
        <jeu id="skyward">
            <nomDeJeu> Skyward Sword </nomDeJeu>
            <dateDeSortie> 2011-11-08 </dateDeSortie>
            <description>The Legend of Zelda : Skyward Sword est un jeu d'action-aventure sur Wii
                dans lequel vous incarnez l'icône de la série : Link. Le héros devra sauver la
                princesse Zelda dans un titre qui met en avant le Wii MotionPlus. Volez à dos de
                Célestrier et combattez des forces maléfiques grâce à une multitude d'objets
                améliorables.</description>
            <note>18</note>
            <multijoueur>Non</multijoueur>
            <theme>Heroic-Fantasy</theme>
            <classification>12</classification>
        </jeu>
        <jeu id="minish">
            <nomDeJeu>Minish Cap</nomDeJeu>
            <dateDeSortie>2004-11-04</dateDeSortie>
            <description>Dans the Legend of Zelda : the Minish Cap, vous incarnez Link, le fils du
                forgeron, dans sa quête pour sauver la princesse Zelda ensorcelée par Vaati. Au
                cours de l'aventure, vous rencontrerez les Minish, un peuple d'êtres minuscules, et
                ferez équipe avec Exelo, le chapeau magicien qui vous aidera à changer de taille.</description>
            <note>17</note>
            <multijoueur>Non</multijoueur>
            <theme>Fantasy</theme>
            <classification>3</classification>
        </jeu>
        <jeu id="swords">
            <nomDeJeu>Four Swords</nomDeJeu>
            <dateDeSortie>02/12/2002</dateDeSortie>
            <description>Dans The Legend of Zelda: Four Swords, Link est invoqué par la princesse
                Zelda pour aider à protéger le royaume d'Hyrule. Link doit s'aventurer à travers de
                nombreux donjons pour vaincre les ennemis et récupérer des fragments de la Triforce.
                Le gameplay repose sur la coopération entre plusieurs joueurs, car jusqu'à quatre
                joueurs peuvent jouer simultanément en utilisant des connexions sans fil. Link est
                accompagné par trois autres versions de lui-même, chacune habillée d'une tunique de
                couleur différente. Ces versions de Link sont appelées Rouge Link, Bleu Link et
                Violet Link. Les quatre Link doivent travailler ensemble pour surmonter les
                obstacles, combattre les ennemis et résoudre les énigmes. Finalement, les quatre
                Link doivent affronter Vaati, un puissant sorcier maléfique, et le vaincre pour
                sauver le royaume d'Hyrule. </description>
            <note>16</note>
            <multijoueur>Oui</multijoueur>
            <classification>7</classification>
        </jeu>
        <jeu id="ocarina">
            <nomDeJeu>Ocarina of Time</nomDeJeu>
            <dateDeSortie>1998-12-11</dateDeSortie>
            <description>Dans The Legend of Zelda: Ocarina of Time, le jeune Link doit voyager dans
                le temps pour empêcher le maléfique Ganondorf de prendre le contrôle du royaume
                d'Hyrule. Link doit parcourir différents lieux du passé et du présent, collecter des
                objets et des armes, résoudre des énigmes et vaincre des ennemis pour progresser
                dans l'histoire. Avec l'aide de la princesse Zelda et du sage Impa, Link doit
                obtenir les trois pierres spirituelles et la Triforce pour pouvoir affronter
                Ganondorf. Finalement, Link doit affronter Ganon dans un combat final pour sauver le
                royaume et rétablir la paix à Hyrule.</description>
            <note>19</note>
            <multijoueur>Non</multijoueur>
            <theme>Heroic-Fantasy</theme>
            <classification>3</classification>
        </jeu>
    </timeline>
    <timeline id="ombre">
        <nomDeTimeline>Le monde de l'ombre et la descendance du héros</nomDeTimeline>
        <jeu id="Majora">
            <nomDeJeu>Majora's Mask</nomDeJeu>
            <dateDeSortie>2000-11-17</dateDeSortie>
            <description>Dans The Legend of Zelda: Majora's Mask, Link est transporté dans le monde
                mystérieux de Termina après avoir été attaqué par le Skull Kid, qui porte un masque
                maléfique connu sous le nom de Majora's Mask. Link doit explorer les différentes
                régions de Termina, collecter des masques magiques, résoudre des énigmes et aider
                les habitants pour empêcher la lune de s'écraser sur la ville de Clock Town. Link
                doit également voyager dans le temps pour revivre les trois jours avant la fin du
                monde et déjouer les plans de Skull Kid et du pouvoir maléfique de Majora's Mask.
                Finalement, Link doit affronter Skull Kid et le puissant pouvoir de Majora's Mask
                pour sauver Termina.</description>
            <note>19</note>
            <multijoueur>Non</multijoueur>
            <theme>Fantasy</theme>
            <classification>3</classification>
        </jeu>
        <jeu id="Twilight">
            <nomDeJeu>Twilight Princess</nomDeJeu>
            <dateDeSortie>2006-12-08</dateDeSortie>
            <description>Dans The Legend of Zelda: Twilight Princess, Link est transporté dans le
                monde sombre et mystérieux du crépuscule après avoir été attaqué par des créatures
                maléfiques. Dans ce monde, il est transformé en loup et doit explorer les
                différentes régions d'Hyrule pour trouver un moyen de briser la malédiction. Link
                est aidé par une mystérieuse créature appelée Midona, qui lui offre son aide pour
                vaincre les forces maléfiques qui menacent le royaume. Au cours de son voyage, Link
                doit résoudre des énigmes, combattre des ennemis et obtenir de nouveaux pouvoirs
                pour avancer dans l'histoire. Finalement, Link doit affronter le puissant sorcier
                Zanto et son maître maléfique, Ganondorf, pour sauver Hyrule et briser la
                malédiction qui le retient prisonnier</description>
            <note>19</note>
            <multijoueur>Non</multijoueur>
            <theme>Fantasy</theme>
            <classification>12</classification>
        </jeu>
        <jeu id="four">
            <nomDeJeu>Four Sword Adventure</nomDeJeu>
            <dateDeSortie>2005-01-07</dateDeSortie>
            <description>Dans The Legend of Zelda: Four Swords Adventures, Link est appelé à sauver
                le royaume d'Hyrule après que le maléfique sorcier Vaati ait été libéré de sa
                prison. Link doit trouver les quatre épées élémentaires pour vaincre Vaati et
                restaurer la paix dans le royaume. Au cours de sa quête, Link doit affronter des
                ennemis redoutables, explorer des donjons remplis de dangers et travailler en équipe
                avec d'autres versions de lui-même pour triompher. Au final, Link doit faire face à
                Vaati dans un combat épique pour restaurer la paix à Hyrule.</description>
            <note>16</note>
            <multijoueur>Oui</multijoueur>
            <theme>Heroic-Fantasy</theme>
            <classification>3</classification>
        </jeu>
    </timeline>
    <timeline id="vent">
        <nomDeTimeline>Le héros du vent et le nouveau monde</nomDeTimeline>
        <jeu id="Wind">
            <nomDeJeu>The Wind Waker</nomDeJeu>
            <dateDeSortie>2003-05-03</dateDeSortie>
            <description>Dans The Legend of Zelda: The Wind Waker, Link doit sauver sa sœur et le
                royaume d'Hyrule de la menace du maléfique Ganondorf. Le monde est maintenant
                recouvert par l'océan et Link doit voyager à bord de son bateau, le Lion Rouge, pour
                explorer les différentes îles et collecter les fragments de la Triforce. Link est
                accompagné par la mystérieuse pirate Tetra et doit affronter de nombreux ennemis,
                résoudre des énigmes et découvrir les secrets du passé pour progresser dans
                l'histoire. Finalement, Link doit affronter Ganondorf et libérer sa sœur et Hyrule
                de son emprise.</description>
            <note>20</note>
            <multijoueur>Non</multijoueur>
            <theme>Heroic-Fantasy</theme>
            <classification>3</classification>
        </jeu>
        <jeu id="Phantom">
            <nomDeJeu>Phantom Hourglass</nomDeJeu>
            <dateDeSortie>2007-10-19</dateDeSortie>
            <description>Dans The Legend of Zelda: Phantom Hourglass, Link est piégé dans le monde
                mystérieux de la Grande Mer, où il doit sauver la princesse Zelda et affronter le
                maléfique Bellum. Link est aidé par Linebeck, un capitaine de bateau lâche et avide,
                et par Ciela, une fée qui le guide tout au long de son aventure. Au cours de son
                périple, Link doit explorer les différentes îles de la Grande Mer, résoudre des
                énigmes et collecter les différents éléments nécessaires pour progresser dans
                l'histoire. Le gameplay utilise les fonctionnalités tactiles de la console Nintendo
                DS pour les contrôles et les énigmes. Finalement, Link doit affronter Bellum pour
                sauver Zelda et le monde de la Grande Mer.</description>
            <note>18</note>
            <multijoueur>Oui</multijoueur>
            <theme>Heroic-Fantasy</theme>
            <classification>7</classification>
        </jeu>
        <jeu id="Spirit">
            <nomDeJeu>Spirit Tracks</nomDeJeu>
            <dateDeSortie>2009-12-11</dateDeSortie>
